### ISSUE TITLE
how to solve problem of EncryptedExoPlayerDemo with more than 2GB files ?

### ISSUE THREAD

**Issue by Navidhp** [moagrius/EncryptedExoPlayerDemo#14]
Hi
Recently I used EncryptedExoPlayerDemo to play encrypted files it has no problem in playing files with less than 2GB volume but unfortunately, I couldn't play more to 2GB files.
Is there any solution for solving this problem.
Thanks so much. 

error : 
```
Source error.
com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
```

**Comment by hardcodet** [comment]
@Navidhp I saw on the exoplayer hub that you solved the issue - do you mind posting your solution?
Thanks!

**Comment by Navidhp** [comment]
@hardcodet Sorry for the delay, please rewrite this repository on your project and follow this :
1- find this method `computeBytesRemaining`
2- If you pay attention to this method, you will notice that it calculates the remaining bytes, but the amount that it can finally calculate is equal to (Integer.MAX_VALUE), That's why it can't read larger files and I changed the inside of the method
```
private void computeBytesRemaining(DataSpec dataSpec) throws IOException {
        File file = new File(dataSpec.uri.getPath());
        if (dataSpec.length != C.LENGTH_UNSET) {
            mBytesRemaining = dataSpec.length;
        } else {
            mBytesRemaining = file.length() > Integer.MAX_VALUE ? file.length() : mInputStream.available();
            if (mBytesRemaining == Integer.MAX_VALUE) {
                mBytesRemaining = C.LENGTH_UNSET;
            }
        }
    }
```
And now it works
