### ISSUE TITLE
Not able to play encrypted video file..

### ISSUE THREAD

**Issue by krishna18787** [moagrius/EncryptedExoPlayerDemo#16]
i am trying to play own encrypted video with specific key..and used same key in your code ..but still facing below error in response..

com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.

**Comment by moagrius** [comment]
That's a very generic error that just means something went wrong...  file type was wrong, decrypted incorrectly, etc.  Make sure you're using all the right pieces - AES/CTR/NoPadding, key is same on both sides, IV is same on both sides, not downloading via HLS, not doing any other en/decryption.  Etc.  Good luck.

**Comment by krishna18787** [comment]
Thanks , I am able to make it run now..Thanks again.
