### ISSUE TITLE
Can't play offline video

### ISSUE THREAD

**Issue by M9Apar** [moagrius/EncryptedExoPlayerDemo#2]
Hi, i tweaked code which is now open video from sdcard and encrypt it and it works perfect for the first time, but for second time when i close and reopen application it gives me following 

com.example.myapplication E/ExoPlayerImplInternal: Source error.
                                                                            com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
                                                                                at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:722)
                                                                                at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:645)
                                                                                at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                at java.lang.Thread.run(Thread.java:841)

can you please suggest me something below is my code for EncryptFileTask

```
public class EncryptFileTask extends AsyncTask<Void, Void, Boolean> {

    private File inputFile;
    private File mFile;
    private Cipher mCipher;

    public EncryptFileTask(File inputFile, File file, Cipher cipher) {

        this.inputFile = inputFile;
        mFile = file;
        mCipher = cipher;
    }

    private boolean downloadAndEncrypt() throws Exception {
        try {
            long startTime = System.currentTimeMillis();
            FileInputStream inputStream = new FileInputStream(inputFile);
            FileOutputStream fileOutputStream = new FileOutputStream(mFile);
            CipherOutputStream cipherOutputStream = new CipherOutputStream(fileOutputStream,
                    mCipher);

            byte buffer[] = new byte[1024 * 1024];
            int bytesRead;
            while ((bytesRead = inputStream.read(buffer)) != -1) {
                cipherOutputStream.write(buffer, 0, bytesRead);
            }

            inputStream.close();
            cipherOutputStream.close();

            float totalTimeInSeconds = (System.currentTimeMillis() - startTime) / 1000f;
            Log.e("Encryption", "Completed for " + inputFile.getName() + " in " + totalTimeInSeconds
                    + " seconds");
            return true;
        } catch (Exception err) {
            err.printStackTrace();
            return false;
        }

//    connection.disconnect();
    }

    @Override
    protected Boolean doInBackground(Void... params) {
        try {
            return downloadAndEncrypt();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    @Override
    protected void onPostExecute(Boolean aVoid) {
        Log.e(getClass().getCanonicalName(), "Encryption done");
        if (aVoid) {
            inputFile.delete();
        }
    }
}
```

and following is my method which play video 

```
public void playVideo(View view) {
        mEncryptedFile = new File(Environment.getExternalStorageDirectory().getAbsolutePath()
                + "/enc_oliver.mp4");
        if (hasFile()) {
            DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter();
            TrackSelection.Factory videoTrackSelectionFactory = new AdaptiveTrackSelection.Factory(
                    bandwidthMeter);
            TrackSelector trackSelector = new DefaultTrackSelector(videoTrackSelectionFactory);
            SimpleExoPlayer player = ExoPlayerFactory.newSimpleInstance(this, trackSelector);
            mSimpleExoPlayerView.setPlayer(player);
            DataSource.Factory dataSourceFactory = new EncryptedFileDataSourceFactory(mCipher,
                    mSecretKeySpec, mIvParameterSpec, bandwidthMeter);
            ExtractorsFactory extractorsFactory = new DefaultExtractorsFactory();
            try {
                Uri uri = Uri.fromFile(mEncryptedFile);
                MediaSource videoSource = new ExtractorMediaSource(uri, dataSourceFactory,
                        extractorsFactory, null, null);
                player.prepare(videoSource);
                player.setPlayWhenReady(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            Log.e("ERROR!!", "File not found");
        }
    }
```

**Comment by androidsoni** [comment]
@kaas3031  @moagrius  Hello , I am facing same issue.Did you got the solution ?

**Comment by M9Apar** [comment]
@androidsoni , yup i found out my mistake which is due to different IV which cause this issue

**Comment by androidsoni** [comment]
@kaas3031 Thank you for reply.If possible,please  provide the sample code .It will be helpful

**Comment by tabish075** [comment]
Store the key in sharedPref and use that key afterwards if you are working with offline videos

**Comment by tabish075** [comment]
Store the key in sharedPref and use that key afterwards if you are working with offline videos Also make IV, Cipher and key static
` public EncryptAndPlay(Context context)
    {
        this.context = context;
        init();
    }`

private void init()
    {
        TinyDB tinyDB = new TinyDB(context);
if(!tinyDB.isKeyExist("VideoKey")) {

            SecureRandom secureRandom = new SecureRandom();
            byte[] key = new byte[16];
            byte[] iv = new byte[16];
            secureRandom.nextBytes(key);
            secureRandom.nextBytes(iv);
            String ke = "cybervaultsecure";
            key = ke.getBytes();
            iv = ke.getBytes();
            tinyDB.putString("VideoKey",ke);

            mSecretKeySpec = new SecretKeySpec(key, AES_ALGORITHM);
            mIvParameterSpec = new IvParameterSpec(iv);

            try {
                mCipher = Cipher.getInstance(AES_TRANSFORMATION);
                mCipher.init(Cipher.DECRYPT_MODE, mSecretKeySpec, mIvParameterSpec);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        else
        {
            byte[] key = new byte[16];
            byte[] iv = new byte[16];

            String ke = tinyDB.getString("VideoKey");
            key = ke.getBytes();
            iv = ke.getBytes();

            mSecretKeySpec = new SecretKeySpec(key, AES_ALGORITHM);
            mIvParameterSpec = new IvParameterSpec(iv);

            try {
                mCipher = Cipher.getInstance(AES_TRANSFORMATION);
                mCipher.init(Cipher.DECRYPT_MODE, mSecretKeySpec, mIvParameterSpec);
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }
