### ISSUE TITLE
How to decrypt and save file locally?

### ISSUE THREAD

**Issue by tabish075** [moagrius/EncryptedExoPlayerDemo#5]
Hi, I am using this for encrypting and saving that file locally, afterwards i'm simply playing my encrypted videos from playVideo() method.. and it's working really fine.
But now i want to decrypt and save this video locally how can i achieve that ? Please suggest

**Comment by moagrius** [comment]
you'd decrypt and save normally using the same cipher - nothing special needed.  a google search will give you thousands of results on how to decrypt and save a file.

**Comment by tabish075** [comment]
Thank you and yes it was easy found the solution :)
