### ISSUE TITLE
Try Your code

### ISSUE THREAD

**Issue by rohanisuhadi** [moagrius/EncryptedExoPlayerDemo#6]
I tried the source code you created. but i get an error

> java.lang.IllegalArgumentException: You need to supply a url to a clear MP4 file to download and encrypt, or modify the code to use a local encrypted mp4
03-02 11:20:17.503 1738-1738/com.test.exoplayer2 W/System.err:     at com.test.exoplayer2.DownloadAndEncryptFileTask.<init>(DownloadAndEncryptFileTask.java:28)
03-02 11:20:17.503 1738-1738/com.test.exoplayer2 W/System.err:     at com.test.exoplayer2.MainActivity.encryptVideo(MainActivity.java:94)
03-02 11:20:17.503 1738-1738/com.test.exoplayer2 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-02 11:20:17.503 1738-1738/com.test.exoplayer2 W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)

Because my in MainActivity.java line 94
new DownloadAndEncryptFileTask(null, mEncryptedFile, encryptionCipher).execute();
in class DownloadAndEncryptFileTask constructor 
`public DownloadAndEncryptFileTask(String url, File file, Cipher cipher) {
    if (url == null || url.isEmpty()) {
      throw new IllegalArgumentException("You need to supply a url to a clear MP4 file to download and encrypt, or modify the code to use a local encrypted mp4");
    }
    mUrl = url;
    mFile = file;
    mCipher = cipher;
  }`
Do I have to fill with url strings?
mohon sertakan panduan penggunaan source code. Supaya orang bisa menggunakan dan mengerti kode kamu. Sehingga dia bisa berkembang dengan cepat. 
Maaf ini hanya saran saya

**Comment by moagrius** [comment]
You need to supply a url to a clear MP4 file to download and encrypt, or modify the code to use a local encrypted mp4

**Comment by rohanisuhadi** [comment]
I am trying to use your code for streaming audio. I upload the encrypted file to the web server. Then I replace local uri with uri form web server, but I get error 
java.io.FileNotFoundException: /encrypted.mp4: open failed: ENOENT (No such file or directory)
and erorr on line code
```
private void setupInputStream() throws FileNotFoundException {
    File encryptedFile = new File(mUri.getPath());
    FileInputStream fileInputStream = new FileInputStream(encryptedFile);
    mInputStream = new StreamingCipherInputStream(fileInputStream, mCipher, mSecretKeySpec, mIvParameterSpec);
  }
```
Maybe you know the error solution of this code

Previously I thank you very much for the code you shared. for me it helps.

**Comment by moagrius** [comment]
looks like the file is not at the path you supplied

**Comment by rohanisuhadi** [comment]
i success try your code for play offline with file encrypted. Fallow below code
`DataSource.Factory dataSourceFactory = new EncryptedFileDataSourceFactory(mCipher, mSecretKeySpec, mIvParameterSpec, bandwidthMeter);

        File file = new File("/storage/sdcard0/Android/data/com.tiketbus.rohani_suhadi.exoplayersederhanasample/files/Download/AndroidTutorialPoint.mp3");

        try {
            Uri uri = Uri.fromFile(file);

            mediaSource = new ExtractorMediaSource(uri, dataSourceFactory, extractorsFactory, null, null);

            player = ExoPlayerFactory.newSimpleInstance(this, trackSelector);

            player.prepare(mediaSource);

            player.setPlayWhenReady(true);

        } catch (Exception e) {
            e.printStackTrace();
        }` 
But i try play with file from server or url (Streaming) so i edit code 
`File file = new File("/storage/sdcard0/Android/data/com.tiketbus.rohani_suhadi.exoplayersederhanasample/files/Download/AndroidTutorialPoint.mp3");` 
to
`File file = new File("http://192.168.0.30/5634_20171231115314.mp3")` 
and get error failed: ENOENT (No such file or directory) because i use code fallow
`File encryptedFile = new File(mUri.toString());
    FileInputStream fileInputStream = new FileInputStream(encryptedFile);
    mInputStream = new StreamingCipherInputStream(fileInputStream, mCipher, mSecretKeySpec, mIvParameterSpec);` 

I am trying to edit your code to play files from the server or streaming, but I do not know what to learn and I change to your code. Because I want the file server also encryption.
Please help

**Comment by moagrius** [comment]
You can't get a remote file like that.  The error is clear.  We don't think this project is likely to be very helpful to you at this point, but good luck!

**Comment by rohanisuhadi** [comment]
After a long time not working on streaming file encryption I finally had an idea and tried to implement it. I tried to find more information about exoplayer and I found the okhttpdatasource library, I think the concept of okhttpdatasource is almost similar to EncryptedFileDataSource that you have created, some equations using inputstream. I tried combining okhttpdatasource with EncryptedFileDataSource, finally successfully playing. But when I ran the audio, I can't move it. I tried to detect errors and try to get a difference. The mInputStream variable in the EncryptedFileDataSource classs I try to get the number of bytes every time the read function reads the result the byte changes but when I mInputStreamdi classs OnlineEncryptedFileDataSource byte it remains 0.
I really don't know what to do for that, and until now I don't have a new idea to solve this problem maybe because I don't know how to work the search bar in exoplayer.
Please help from Mr. Moagrius. A little information might make me have an idea to solve my problem.
Thank you for your attention and assistance.
this sample code https://github.com/rohanisuhadi/DemoStreamingEncryptionExoplayer
