### ISSUE TITLE
Online EncryptedExoplayerDemo

### ISSUE THREAD

**Issue by rohanisuhadi** [moagrius/EncryptedExoPlayerDemo#7]
After a long time not working on streaming file encryption I finally had an idea and tried to implement it. I tried to find more information about exoplayer and I found the okhttpdatasource library, I think the concept of okhttpdatasource is almost similar to EncryptedFileDataSource that you have created, some equations using inputstream. I tried combining okhttpdatasource with EncryptedFileDataSource, finally successfully playing. But when I ran the audio, I can't move it. I tried to detect errors and try to get a difference. The mInputStream variable in the EncryptedFileDataSource classs I try to get the number of bytes every time the read function reads the result the byte changes but when I mInputStreamdi classs OnlineEncryptedFileDataSource byte it remains 0.
I really don't know what to do for that, and until now I don't have a new idea to solve this problem maybe because I don't know how to work the search bar in exoplayer.
Please help from Mr. Moagrius. A little information might make me have an idea to solve my problem.
Thank you for your attention and assistance.
this sample code https://github.com/rohanisuhadi/DemoStreamingEncryptionExoplayer/blob/master/app/src/main/java/com/example/suhadi/demostreamingencryptionexoplayer/OnlineEncryptedFileDataSource.java

**Comment by moagrius** [comment]
Honestly I'm not clear what your question is, but I doubt I can help.  This example is just showing how to play files locally encrypted with AES using ExoPlayer.  Anything outside of that scope should probably be addressed to the ExoPlayer maintainer.  Sorry; good luck

**Comment by rohanisuhadi** [comment]
I do not understand how to work for the seekbar when audio video is playing. I ask you to give an explanation about how the search bar works in exoplayer.

**Comment by moagrius** [comment]
the seekbar moves the stream pointer to the appropriate position and tries to start playing the stream from that position.  again, not really a question for this repo.

**Comment by rohanisuhadi** [comment]
Thank you very much

**Comment by moagrius** [comment]
sure, sorry i'm not a great source of help here.  good luck!
