### ISSUE TITLE
When play second times give error.

### ISSUE THREAD

**Issue by chnouman** [moagrius/EncryptedExoPlayerDemo#8]
first time download the video file and play perfectly but when I close the app and hit download button it correctly says file already found no need to download again and when I hit play it gives me following error:
`2018-12-23 20:05:36.879 24151-25913/com.test.exoplayer2 E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: None of the available extractors (MatroskaExtractor, FragmentedMp4Extractor, Mp4Extractor, Mp3Extractor, AdtsExtractor, Ac3Extractor, TsExtractor, FlvExtractor, OggExtractor, PsExtractor, WavExtractor) could read the stream.
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractorHolder.selectExtractor(ExtractorMediaPeriod.java:705)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:628)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)`

**Comment by chnouman** [comment]
@moagrius

**Comment by Navidhp** [comment]
@chnouman how to fix that?

**Comment by chnouman** [comment]
@Navidhp downloaded file was corrupt.

**Comment by Navidhp** [comment]
@chnouman bro, are you encrypt the file in the server or in a client ?

**Comment by chnouman** [comment]
@Navidhp I was doing this on the client-side.

**Comment by Navidhp** [comment]
@chnouman are you problem with large file encryption (2GB or higher then) ? I see this error with large

**Comment by chnouman** [comment]
@Navidhp  issue happened to me with large files but when my download failed in between etc. Otherwise, it works perfectly

**Comment by Navidhp** [comment]
@chnouman bro can you help me and share your encryption code and exoplayer ?? I have challenged with issue in 1 weak

**Comment by chnouman** [comment]
@Navidhp I'll try to find that piece of code and share it with you.

**Comment by Navidhp** [comment]
@chnouman my deepest thank goes to you for your help

**Comment by chnouman** [comment]
Hi @Navidhp magic things are happening here. I hope it will help you some how.



```
import android.support.annotation.NonNull;
import android.util.Log;
import android.widget.Toast;
import org.reactivestreams.Subscriber;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.concurrent.TimeUnit;
import javax.crypto.Cipher;
import javax.crypto.CipherOutputStream;
import io.reactivex.Observer;
import io.reactivex.android.schedulers.AndroidSchedulers;
import io.reactivex.disposables.Disposable;
import io.reactivex.functions.Consumer;
import io.reactivex.functions.Function;
import io.reactivex.schedulers.Schedulers;
import okhttp3.OkHttpClient;
import okhttp3.ResponseBody;
import retrofit2.Retrofit;
import retrofit2.adapter.rxjava2.RxJava2CallAdapterFactory;

public class DownloadAPI {
    private static final String TAG = "DownloadAPI";
    private static final int DEFAULT_TIMEOUT = 15;
    public Retrofit retrofit;

    public DownloadAPI(String url, DownloadProgressListener listener) {

        DownloadProgressInterceptor interceptor = new DownloadProgressInterceptor(listener);

        OkHttpClient client = new OkHttpClient.Builder()
                .addInterceptor(interceptor)
                .retryOnConnectionFailure(true)
                .connectTimeout(DEFAULT_TIMEOUT, TimeUnit.SECONDS)
                .build();


        retrofit = new Retrofit.Builder()
                .baseUrl(url)
                .client(client)
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .build();
    }

    public void downloadVideo(@NonNull String url, final File file, Cipher mCipher, Observer subscriber) {
        Log.d(TAG, "downloadVideo: " + url);

        retrofit.create(APIInterface.class)
                .download(url)
                .subscribeOn(Schedulers.io())
                .unsubscribeOn(Schedulers.io())
                .map(responseBody -> responseBody.byteStream())
                .observeOn(Schedulers.computation())
                .doOnNext(new Consumer<InputStream>() {
                    @Override
                    public void accept(InputStream inputStream) throws Exception {

                        FileOutputStream fileOutputStream = new FileOutputStream(file);
                        CipherOutputStream cipherOutputStream = new CipherOutputStream(fileOutputStream, mCipher);

                        byte buffer[] = new byte[1024 * 1024];
                        int bytesRead;
                        int count = 0;
                        double sumCount = 0.0;
                        while ((bytesRead = inputStream.read(buffer)) != -1) {
                            Log.d(getClass().getCanonicalName(), "reading from http... ");
                            cipherOutputStream.write(buffer, 0, bytesRead);
                            count = bytesRead;
                            sumCount += count;
                        }

                        inputStream.close();
                        cipherOutputStream.close();
                    }
                })
                .doOnError(throwable -> {
                    Log.d("DownloadTT", "doOnError: "+throwable.getMessage());
                    throwable.printStackTrace();
                })
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(subscriber);
    }

    public interface DownloadProgressListener {
        void update(long bytesRead, long contentLength, boolean done);
    }
}``
```

**Comment by Navidhp** [comment]
@chnouman thank bro. would you mind sending exoplayer source please ? actually i needed this
